package(default_visibility = ["//visibility:public"])

test_suite(
    name = "all_tests",
    tests = [
        "//tests/unit:test_behaviors",
        "//tests/unit:test_hardware_adapters",
        "//tests/unit:test_infeed",
        "//tests/unit:test_tray",
        "//tests/unit:test_workpiece",
    ],
)
