# proto-file: intrinsic/assets/scene_objects/proto/scene_object_manifest.proto
# proto-message: intrinsic_proto.scene_objects.SceneObjectManifest

metadata {
  id {
    name: "camera_mount"
    package: "ai.intrinsic"
  }
  vendor {
    display_name: "intrinsic"
  }
  display_name: "camera_mount"
}
