load("@ioc//incode/intrinsic_sdk/intrinsic/assets/scene_objects/build_defs:scene_object.bzl", "intrinsic_scene_object")

package(default_visibility = ["//visibility:public"])

intrinsic_scene_object(
    name = "cnc_enclosure",
    manifest = ":cnc_enclosure_manifest.textproto",
    scene_object = "@ioc//intrinsic/resources/catalog/resourcedata/product/imts:cnc_enclosure",
)
