package(default_visibility = ["//visibility:public"])

exports_files([
    "align_robot.updates.pbtxt",
    "cnc_enclosure.updates.pbtxt",
    "flowstate_ros_bridge_manifest.textproto",
    "icon_config.textproto",
    "lab_bb_01_gemini_device_config.textproto",
    "lab_bb_01_orbbec_gemini.updates.pbtxt",
    "omts_camera_mount.updates.pbtxt",
    "omts_gemini_device_config.textproto",
    "orbbec_gemini_driver_manifest.textproto",
    "scene.updates.pbtxt",
    "schunk.updates.pbtxt",
    "ur_module.attachments.updates.pbtxt",
    "ur_module_config.textproto",
    "pose_estimator_config.textproto",
])
