package(default_visibility = ["//visibility:public"])

exports_files([
    "align_robot.updates.pbtxt",
    "icon_config.textproto",
    "lab_bb_01_gemini_device_config.textproto",
    "omts_gemini_device_config.textproto",
    "scene.updates.pbtxt",
    "ur_module.attachments.updates.pbtxt",
    "ur_module_config.textproto",
])
