updates {
  update_transform {
    node_a {
      by_name {
        frame {
          object_name: "ur_module"
          frame_name: "flange"
        }
      }
    }
    node_b {
      by_name {
        object {
          object_name: "orbbec_camera"
        }
      }
    }
    node_to_update {
      by_name {
        object {
          object_name: "orbbec_camera"
        }
      }
    }
    a_t_b {
      position {
        x: 0.02480645006724921
        y: 0.09346009100077277
        z: 0.07805860230989713
      }
      orientation {
        x: 0.005611246057026518
        y: 0.17827670629091044
        z: -0.9839591103971416
        w: -0.003224744674871583
      }
    }
  }
}
updates {
  reparent_object {
    object {
      by_name {
        object_name: "orbbec_camera"
      }
    }
    new_parent {
      reference {
        by_name {
          object_name: "ur_module"
        }
      }
      entity_filter {
        include_final_entity: true
      }
    }
  }
}
