# proto-file: intrinsic/world/public/proto/object_world_updates.proto
# proto-message: intrinsic_proto.world.ObjectWorldUpdates

updates {
  create_frame {
    new_frame_name: "grasp"
    parent_t_new_frame {
      position {
        x: 0.15
        y: 0.25
        z: 0.71
      }
      orientation {
        x: 1.0
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "pre_grasp"
    parent_t_new_frame {
      position {
        x: 0.15
        y: 0.25
        z: 0.73
      }
      orientation {
        x: 1.0
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "pre_place_vise"
    parent_t_new_frame {
      position {
        x: 0.47
        y: 0.37
        z: 0.78
      }
      orientation {
        x: 0.7071
        y: 0.7071
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "place_vise"
    parent_t_new_frame {
      position {
        x: 0.47
        y: 0.37
        z: 0.7
      }
      orientation {
        x: 0.7071
        y: 0.7071
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "machine_approach"
    parent_t_new_frame {
      position {
        x: 0.35
        y: 0.4
        z: 0.8
      }
      orientation {
        x: 0.7071
        y: 0.7071
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "view"
    parent_t_new_frame {
      position {
        x: 0.3433
        y: 0.3786
        z: 0.9078
      }
      orientation {
        x: -0.2667
        y: -0.9585
        z: 0.1
        w: 0.0092
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  update_transform {
    node_a {
      by_name {
        object {
          object_name: "root"
        }
      }
    }
    node_b {
      by_name {
        object {
          object_name: "raw_stock_2x3x5"
        }
      }
    }
    node_to_update {
      by_name {
        object {
          object_name: "raw_stock_2x3x5"
        }
      }
    }
    a_t_b {
      position {
        x: 0.25
        y: 0.25
        z: 0.71
      }
      orientation {
        x: 0.7071
        y: 0.0
        z: 0.0
        w: 0.7071
      }
    }
  }
}
updates {
  update_entity_properties {
    entity {
      reference {
        by_name {
          object_name: "raw_stock_2x3x5"
        }
      }
      entity_filter {
        include_base_entity: true
      }
    }
    geometry_component {
      named_geometries {
        key: "Intrinsic_Collision"
        value {
          named_geometries {
            key: "raw_stock_collision"
            value {
              geometry {
                inline_geometry_data {
                  exact_geometry {
                    primitive_set {
                      primitives {
                        shape {
                          box {
                            size {
                              x: 0.02
                              y: 0.0762
                              z: 0.0508
                            }
                          }
                        }
                        ref_t_shape {
                          matrix4d {
                            rows: 4
                            cols: 4
                            values: 1.0
                            values: 0.0
                            values: 0.0
                            values: 0.0
                            values: 0.0
                            values: 1.0
                            values: 0.0
                            values: 0.0
                            values: 0.0
                            values: 0.0
                            values: 1.0
                            values: 0.0
                            values: 0.0
                            values: 0.0
                            values: 0.0
                            values: 1.0
                          }
                        }
                      }
                    }
                  }
                }
              }
              ref_t_shape {
                matrix4d {
                  rows: 4
                  cols: 4
                  values: 1.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 1.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 1.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 1.0
                }
              }
            }
          }
        }
      }
      named_geometries {
        key: "Intrinsic_Visual"
        value {
          named_geometries {
            key: "2x3x5_raw_stock"
            value {
              geometry {
                geo_ref {
                  exact_geometry_ref: "intcas://20a124b44d60fb5a77b28ad345d10d0edf659a792a0cb042d537be1690589c2eb4541fc3c4d62e5f377844a6124d3228af0a5b51658336b5e638313cfcd2efb6"
                  renderable_ref: "intcas://41f76592886543f9a23653dc48d7e2fa664be45014bd8519eaecea759ef21ddf74fbbe06ce0593e05dfb64d43326f4aa3ffe15f5ddc102d8da0eb108f9629e5b"
                  keep_renderable: true
                }
              }
              ref_t_shape {
                matrix4d {
                  rows: 4
                  cols: 4
                  values: 1.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 1.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 1.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 0.0
                  values: 1.0
                }
              }
            }
          }
        }
      }
    }
  }
}

