package(default_visibility = ["//visibility:public"])

# Developer and operational tool targets
# - //tools/calibration:calibrate_camera
# - //tools/jogging:jog_interactive
# - //tools/jogging:move_to_frame
# - //tools/jogging:store_frame
# - //tools/jogging:store_joint_config
# - //tools/machine:control_machine
# - //tools/world:inspect_world
